# -*- coding: utf-8 -*-
"""majorprojec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNW7xfv1YIZNdaQDwEpWTR7wy4sG8vnz
"""

import tensorflow as tf

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import Xception
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.applications import MobileNetV2

train_dir = '/content/drive/MyDrive/train_set'
validation_dir = '/content/drive/MyDrive/test_set'

datagen = ImageDataGenerator(
    rescale=1.0 / 255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2,
)

train_generator = datagen.flow_from_directory(
    '/content/drive/MyDrive/train_set',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training',
)

validation_generator = datagen.flow_from_directory(
    '/content/drive/MyDrive/test_set (1)',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation',
)

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import platform

model = tf.keras.applications.MobileNetV2()
print(model)

datagen = ImageDataGenerator(
    rescale=1.0 / 255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2,
)

train_generator = datagen.flow_from_directory(
    '/content/drive/MyDrive/train_set',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training',
)

validation_generator = datagen.flow_from_directory(
    '/content/drive/MyDrive/test_set (1)',
    target_size=(224, 224),
    batch_size=4,
    class_mode='categorical',
    subset='validation',
)

base_model = MobileNetV2(weights='imagenet', include_top=False)
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(512, activation='relu')(x)
predictions = Dense(8, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=predictions)

fine_tune_at = 50
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
              loss='categorical_crossentropy',
              metrics=['accuracy'])
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

model.fit(train_generator, validation_data=validation_generator, epochs=50)

class_names = ['cellulitis', 'impetigo', 'athlete-foot','nail-fungus','ring worm','cutaneous-larva-migrans','chickenpox','shingles']

import numpy as np
from PIL import Image

def load_and_preprocess_image(image_path, target_size=(224, 224)):
    img = Image.open(image_path)
    img = img.resize(target_size)
    img = np.array(img) / 255.0  # Normalize pixel values
    return img

test_image = load_and_preprocess_image('/content/drive/MyDrive/train_set/VI-shingles/101_VI-shingles (20).jpg')  # Implement this function

# Get predictions
predictions = model.predict(np.expand_dims(test_image, axis=0))
predicted_class_index = np.argmax(predictions)
predicted_class_name = class_names[predicted_class_index]

print(f"Predicted class: {predicted_class_name}")

test_image = load_and_preprocess_image('/content/drive/MyDrive/train_set/PA-cutaneous-larva-migrans/101_PA-cutaneous-larva-migrans (60).jpg')  # Implement this function

# Get predictions
predictions = model.predict(np.expand_dims(test_image, axis=0))
predicted_class_index = np.argmax(predictions)
predicted_class_name = class_names[predicted_class_index]

print(f"Predicted class: {predicted_class_name}")

model.save("skin_disease_model_1.h5")